version: "3"

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - task --list-all

  run-matrix:
    desc: "Run lab1-5 program"
    aliases: [runm]
    cmds:
      - go run ./cmd/module1/main.go

  run-game:
    desc: "Run lab6-rr program"
    aliases: [rung]
    cmds:
      - go run ./cmd/module2/main.go
